name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master' 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd /var/www/html/workout_api/ && git pull
    
